### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by carolinebridge** [cmdcolin/jbrowse-plugin-civic-api#3]
Navigating to the demo link and opening the CIVIC track yields and error:

![image](https://github.com/cmdcolin/jbrowse-plugin-civic-api/assets/83305007/b5424dae-d4f2-4702-be80-c2fcce49e33d)

No console message, might be config related.

Installing the plugin on a local session and opening the track works as expected.

**Comment by cmdcolin** [comment]
thanks for catching this, I published a new version that should fix (just updated the demo config)

the cdn for unpkg may take a minute to realize it is the latest but maybe can close
